=== JensBrunken/psh/resource/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1" elementFormDefault="qualified">

    <xs:element name="psh" type="pshConfig"/>

    <xs:complexType name="pshConfig" vc:minVersion="1.1">
        <xs:all>
            <xs:element name="header" type="xs:string" minOccurs="0"/>
            <xs:element name="placeholder" type="vars" minOccurs="0"/>

            <xs:element name="path" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="template" type="template" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="environment" type="environment" minOccurs="0" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="environment">
        <xs:all>
            <xs:element name="placeholder" type="vars" minOccurs="0" />
            <xs:element name="path" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="template" type="template" minOccurs="0" maxOccurs="unbounded"/>
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="template">
        <xs:attribute name="source" type="xs:string" use="required"/>
        <xs:attribute name="destination" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="vars">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="const" type="var" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="dynamic" type="var" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="var">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== JensBrunken/psh/tests/Acceptance/_app/.psh.xml
<?xml version="1.0" encoding="UTF-8"?>
<psh xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../resource/config.xsd">

    <header>SHOPWARE PHP-SH</header>
    <template source="templates/test.tpl" destination="result.txt"/>
    <path>scripts/</path>
    <placeholder>
        <const name="ENV">prod</const>
        <const name="TEST">prod</const>
        <const name="HOST">http://www.selfish.de</const>
        <const name="NUMBER">1701</const>
        <dynamic name="ID">id</dynamic>
        <dynamic name="LL">ls -ahl</dynamic>
    </placeholder>
    <environment name="test">
        <path>envpath/</path>
        <path>envpath2/</path>
        <placeholder>
            <const name="ENV">test</const>
        </placeholder>
    </environment>
</psh>
